export default {
  getMajor: '/getMajor',
  createProject: '/createProject',
  getGradeList: '/getAllGrade',
  getProjectList: '/getProjectList',
  delProject: '/delProject',
  updateObject: '/updateObject',
  updateRequirement: '/updateRequirement',
  addPoint: '/addPoint',
  saveTableOne: '/jys/tableOne',
  saveTableTwo: '/jys/tableTwo',
  getTable1RowCol: '/getRowColData',
  getTable2RowCol: '/getTable2RowCol',
  // getAllPoint: '/getAllPoint',
  getCourse: '/getAllCourse',
  addCurrRelationship: '/addCurrRelationship',
  delCurrRelationship: '/delCurrRelationship',

  getProjectDetail: '/getProjectDetail',
  getObjectData: '/getObjectData',
  getRequirementById: '/getRequirementById',
}