export default {
  START_LOGIN: 'START_LOGIN',  // 登录中
  LOGIN_SUCCESS: 'LOGIN_SUCCESS', // 登录成功
  LOGIN_FAILED: 'LOGIN_FAILED', // 登录失败
  LOGOUT: 'LOGOUT',
  SET_USER: 'SET_USER',
  CHANGE_TYPE: 'CHANGE_TYPE', // 主题切换
}